// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HLhzFQm99y8GmAS3GUTOx4ksIvPzr9o',
    appId: '1:713043779992:web:bef816a36d1735e1a68bed',
    messagingSenderId: '713043779992',
    projectId: 'greencare-fbe54',
    authDomain: 'greencare-fbe54.firebaseapp.com',
    storageBucket: 'greencare-fbe54.firebasestorage.app',
    measurementId: 'G-4W5Z32SKRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1y2Ex9_xd5hs_jp5A5vfLKJNuIe_5zoo',
    appId: '1:713043779992:android:ebc3910b8a6ecb19a68bed',
    messagingSenderId: '713043779992',
    projectId: 'greencare-fbe54',
    storageBucket: 'greencare-fbe54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBpIffXQpquaka5gcnmljTDSX1aHJsOE',
    appId: '1:713043779992:ios:f11b11b9ed43e6c7a68bed',
    messagingSenderId: '713043779992',
    projectId: 'greencare-fbe54',
    storageBucket: 'greencare-fbe54.firebasestorage.app',
    iosClientId: '713043779992-hmldoqsm981ogndl9athunr9k81rb53d.apps.googleusercontent.com',
    iosBundleId: 'com.example.greencareFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8HLhzFQm99y8GmAS3GUTOx4ksIvPzr9o',
    appId: '1:713043779992:web:20eacaa31ebf3855a68bed',
    messagingSenderId: '713043779992',
    projectId: 'greencare-fbe54',
    authDomain: 'greencare-fbe54.firebaseapp.com',
    storageBucket: 'greencare-fbe54.firebasestorage.app',
    measurementId: 'G-C84D2Z6FVX',
  );
}
